export const ROUTE_PATH = Object.freeze({
  ROOT: '/',
  AUTH: '/auth',
  LOGIN: '/login',
  REGISTRATION: '/registration',
  LOCATION_SEARCH: '/locationSearch',
  HOME: '/home',
  LOCATION_SETTING: '/locationSetting',
  SALES_LIST: '/sales',
  WISH_LIST: '/heart',
  CHAT: '/Chat',
  CHAT_ROOM: '/chatRoom/:id',
  ACCOUNT: '/account',
  NEW_PRODUCT: '/newproduct',
  CATEGORY: '/category',
  PRODUCT_DETAIL: '/productDetail/:id',
});
